version: '3'


services:
  web:
    build: wheat_dashboard_iksan
    command: gunicorn dashboard_weather.wsgi:application --bind 0.0.0.0:8000
#    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
