version: '3'


services:
  web:
    build: .
    command: python3 -u weather_data_fastapi.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    environment:
       TZ: Asia/Seoul

