version: '3'

services:
  web:
    build: .
    command: gunicorn dashboard_weather.wsgi:application --bind 0.0.0.0:8000
#    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
      - ./:/usr/src/app/
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
    ports:
      - 8070:80
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:

